server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.190:8848 #配置Nacos地址
        # 集群配置：换成nginx的1111端口，做集群
        #server-addr: 192.168.1.190:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'


